name: Gradle Build & Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Generate the Gradle wrapper (8.8) so we can use ./gradlew in this run
      - name: Generate Gradle wrapper (8.8)
        run: |
          gradle wrapper --gradle-version 8.8
          chmod +x ./gradlew

      - name: Setup JFrog CLI (OIDC)
        id: jfrog-setup
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: tpaz1/gradle-ci-example@github
          # oidc-audience: jfrog-github   # only if configured in JFrog

      - name: Build & Publish to Artifactory
        env:
          JF_USER: ${{ steps.jfrog-setup.outputs.oidc-user }}
          JF_PASSWORD: ${{ steps.jfrog-setup.outputs.oidc-token }}
        run: |
          ./gradlew clean build artifactoryPublish --info --stacktrace
