jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0     # needed if your script reads tags/branch

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup JFrog CLI (OIDC)
        id: jfrog-setup
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: tpaz1/gradle-ci-example@github
          # oidc-audience: jfrog-github   # only if you configured it

      - name: Build & Publish
        env:
          JF_ACCESS_TOKEN: ${{ steps.jfrog-setup.outputs.oidc-token }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean build artifactoryPublish --info
